# # Install pre-commit hooks via
# pre-commit install

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: double-quote-string-fixer
    exclude: &exclude_files >
      (?x)^(
          tests/data/.*|
          examples/data/.*|
      )$
  - id: end-of-file-fixer
    exclude: *exclude_files
  - id: fix-encoding-pragma
    exclude: *exclude_files
  - id: mixed-line-ending
    exclude: *exclude_files
  - id: trailing-whitespace
    exclude: *exclude_files

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v1.5.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, "2", --preserve-quotes]

- repo: https://github.com/adrienverge/yamllint
  rev: v1.25.0
  hooks:
  - id: yamllint

- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.30.0
  hooks:
  # yapf = yet another python formatter
  - id: yapf
    name: yapf
    types: [python]
    exclude: >
      (?x)^(
          docs/.*|
      )$
    args: ['-i']

- repo: local
  hooks:
  # prospector: collection of linters
  - id: pylint
    name: pylint
    entry: pylint
    types: [python]
    language: system
